name: System roots

on:
  push:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install android-gcc-cross
      run: |
        declare -r PINO_TAG='gcc-16'
        declare -r PINO_TARBALL='/tmp/toolchain.tar.xz'
        declare -r PINO_URL="https://github.com/AmanoTeam/android-gcc-cross/releases/download/${PINO_TAG}/x86_64-unknown-linux-gnu.tar.xz"
            
        curl --connect-timeout '10' --retry '15' --retry-all-errors --fail --silent --location --url "${PINO_URL}" --output "${PINO_TARBALL}"
        tar --directory="$(dirname "${PINO_TARBALL}")" --extract --file="${PINO_TARBALL}"
        
        echo '/tmp/android-gcc-cross/bin' >> "${GITHUB_PATH}"
    - name: Generate sysroots
      run: bash -v './sysroot.sh'
    - name: Create release
      uses: softprops/action-gh-release@master
      with:
        tag_name: sysroot
        name: Android system roots
        files: /tmp/*.tar.xz*
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        body: "* Android system roots"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
